# Generated by Django 4.2.30 on 2026-06-03 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wp_number', models.CharField(max_length=50, verbose_name='底稿编号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review', '复核中'), ('finalised', '已审定')], default='draft', max_length=20, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('content', models.JSONField(default=dict, verbose_name='内容')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workpapers', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpapers', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '审计底稿',
                'verbose_name_plural': '审计底稿',
                'db_table': 'workpapers_workpaper',
                'ordering': ['wp_number'],
            },
        ),
    ]
