# Generated by Django 4.2.30 on 2026-06-03 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(max_length=50, verbose_name='分录编号')),
                ('description', models.TextField(verbose_name='说明')),
                ('status', models.CharField(choices=[('proposed', '待提议'), ('approved', '已批准'), ('posted', '已过账'), ('rejected', '已驳回')], default='proposed', max_length=20, verbose_name='状态')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_entries', to=settings.AUTH_USER_MODEL, verbose_name='编制人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjusting_entries', to='projects.project', verbose_name='项目')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entries', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '调整分录',
                'verbose_name_plural': '调整分录',
                'db_table': 'adjustments_adjustingentry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='借方金额')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='贷方金额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_lines', to='ledger.account', verbose_name='科目')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='adjustments.adjustingentry', verbose_name='调整分录')),
            ],
            options={
                'verbose_name': '调整分录行',
                'verbose_name_plural': '调整分录行',
                'db_table': 'adjustments_adjustmentline',
            },
        ),
    ]
