# Generated by Django 4.2.30 on 2026-06-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='科目代码')),
                ('name', models.CharField(max_length=255, verbose_name='科目名称')),
                ('category', models.CharField(choices=[('asset', '资产'), ('liability', '负债'), ('equity', '所有者权益'), ('revenue', '收入'), ('expense', '费用')], default='asset', max_length=20, verbose_name='科目类别')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ledger.account', verbose_name='上级科目')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '会计科目',
                'verbose_name_plural': '会计科目',
                'db_table': 'ledger_account',
                'ordering': ['code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=20, verbose_name='期间')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='借方金额')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='贷方金额')),
                ('description', models.TextField(blank=True, verbose_name='摘要')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='来源文件')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.account', verbose_name='科目')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '账簿分录',
                'verbose_name_plural': '账簿分录',
                'db_table': 'ledger_entry',
                'ordering': ['-created_at'],
            },
        ),
    ]
