# Generated by Django 4.2.30 on 2026-06-04 07:44

from django.db import migrations, models
import django.db.models.deletion


def init_base_currency(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Currency = apps.get_model('ledger', 'Currency')
    for project in Project.objects.all():
        Currency.objects.get_or_create(
            project=project,
            code='CNY',
            defaults={'name': '人民币', 'is_base': True, 'exchange_rate': 1}
        )


def reverse_init(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, verbose_name='币种代码')),
                ('name', models.CharField(max_length=50, verbose_name='币种名称')),
                ('is_base', models.BooleanField(default=False, verbose_name='是否本位币')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='汇率')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '币种',
                'verbose_name_plural': '币种',
                'db_table': 'ledger_currency',
                'ordering': ['code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.RunPython(init_base_currency, reverse_init),
    ]
