# Generated by Django 4.2.30 on 2026-06-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workpapers', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_number', models.CharField(max_length=20, verbose_name='附注编号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('linked_workpapers', models.ManyToManyField(blank=True, related_name='linked_notes', to='workpapers.workpaper', verbose_name='关联底稿')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_drafts', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '附注草稿',
                'verbose_name_plural': '附注草稿',
                'db_table': 'notes_notedraft',
                'ordering': ['note_number'],
            },
        ),
    ]
