# Generated by Django 4.2.30 on 2026-06-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='期初借方')),
                ('opening_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='期初贷方')),
                ('period_movement_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='本期借方发生额')),
                ('period_movement_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='本期贷方发生额')),
                ('adjusted_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='调整后借方')),
                ('adjusted_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='调整后贷方')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_snapshots', to='ledger.account', verbose_name='科目')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '试算平衡表',
                'verbose_name_plural': '试算平衡表',
                'db_table': 'trial_balance_snapshot',
                'ordering': ['account__code'],
                'unique_together': {('project', 'account')},
            },
        ),
    ]
