# Generated by Django 4.2.30 on 2026-06-03 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('import_type', models.CharField(choices=[('tb', '科目余额表'), ('je', '序时账')], max_length=10, verbose_name='导入类型')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('preview', '预览中'), ('validated', '已校验'), ('committed', '已入库'), ('failed', '失败')], default='uploaded', max_length=20, verbose_name='状态')),
                ('overwrite_mode', models.CharField(choices=[('append', '追加'), ('replace', '覆盖')], default='append', max_length=10, verbose_name='覆盖模式')),
                ('period', models.CharField(blank=True, max_length=20, verbose_name='会计期间')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('parsed_rows', models.PositiveIntegerField(default=0, verbose_name='解析行数')),
                ('error_rows_count', models.PositiveIntegerField(default=0, verbose_name='错误行数')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('validation_summary', models.JSONField(blank=True, default=dict, verbose_name='校验摘要')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='projects.project', verbose_name='项目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'db_table': 'imports_batch',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'period', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UnauditedJE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_date', models.DateField(blank=True, null=True, verbose_name='凭证日期')),
                ('voucher_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='凭证号')),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='行号')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('account_code', models.CharField(db_index=True, max_length=50, verbose_name='科目编码')),
                ('account_name', models.CharField(blank=True, max_length=255, verbose_name='科目名称')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='借方')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='贷方')),
                ('aux_fields', models.JSONField(blank=True, default=dict, verbose_name='辅助核算')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_rows', to='imports.importbatch', verbose_name='导入批次')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unaudited_jes', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '未审序时账',
                'verbose_name_plural': '未审序时账',
                'db_table': 'imports_unaudited_je',
                'ordering': ['voucher_date', 'voucher_no', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='ImportErrorRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(verbose_name='行号')),
                ('raw_data', models.JSONField(default=dict, verbose_name='原始数据')),
                ('error_type', models.CharField(choices=[('format', '格式错误'), ('balance', '不平衡'), ('duplicate', '重复科目'), ('consistency', '期间不一致'), ('other', '其他')], max_length=20, verbose_name='错误类型')),
                ('error_message', models.TextField(verbose_name='错误信息')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已解决')),
                ('resolved_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='修正后数据')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_errors', to='imports.importbatch', verbose_name='导入批次')),
            ],
            options={
                'verbose_name': '导入错误行',
                'verbose_name_plural': '导入错误行',
                'db_table': 'imports_error_row',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='UnauditedTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(db_index=True, max_length=50, verbose_name='科目编码')),
                ('account_name', models.CharField(max_length=255, verbose_name='科目名称')),
                ('opening_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='期初借方')),
                ('opening_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='期初贷方')),
                ('period_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='本期借方')),
                ('period_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='本期贷方')),
                ('closing_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='期末借方')),
                ('closing_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='期末贷方')),
                ('direction', models.CharField(blank=True, choices=[('debit', '借'), ('credit', '贷')], max_length=10, verbose_name='余额方向')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tb_rows', to='imports.importbatch', verbose_name='导入批次')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unaudited_tbs', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '未审科目余额表',
                'verbose_name_plural': '未审科目余额表',
                'db_table': 'imports_unaudited_tb',
                'ordering': ['account_code'],
                'unique_together': {('import_batch', 'account_code')},
            },
        ),
    ]
