# Generated by Django 4.2.30 on 2026-06-04 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_currency_code(apps, schema_editor):
    UnauditedTB = apps.get_model('imports', 'UnauditedTB')
    UnauditedJE = apps.get_model('imports', 'UnauditedJE')
    UnauditedTB.objects.filter(currency_code='').update(currency_code='CNY')
    UnauditedJE.objects.filter(currency_code='').update(currency_code='CNY')


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imports', '0001_initial'),
        ('ledger', '0002_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importbatch',
            unique_together={('project', 'period', 'import_type', 'version')},
        ),
        migrations.AddField(
            model_name='importbatch',
            name='warning_rows_count',
            field=models.PositiveIntegerField(default=0, verbose_name='警告行数'),
        ),
        migrations.AddField(
            model_name='importerrorrow',
            name='severity',
            field=models.CharField(choices=[('error', '错误'), ('warning', '警告')], default='error', max_length=10, verbose_name='严重程度'),
        ),
        migrations.AddField(
            model_name='unauditedje',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='币种代码'),
        ),
        migrations.AddField(
            model_name='unauditedje',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='汇率'),
        ),
        migrations.AddField(
            model_name='unauditedje',
            name='foreign_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='原币贷方'),
        ),
        migrations.AddField(
            model_name='unauditedje',
            name='foreign_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='原币借方'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='closing_balance_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='期末计算差异'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='币种代码'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='direction_conflict',
            field=models.BooleanField(default=False, verbose_name='方向冲突标记'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='direction_inferred',
            field=models.CharField(blank=True, choices=[('debit', '借'), ('credit', '贷')], max_length=10, verbose_name='系统推断方向'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='汇率'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='foreign_closing_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='原币期末贷方'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='foreign_closing_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='原币期末借方'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='foreign_opening_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='原币期初贷方'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='foreign_opening_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='原币期初借方'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='foreign_period_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='原币本期贷方'),
        ),
        migrations.AddField(
            model_name='unauditedtb',
            name='foreign_period_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='原币本期借方'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', '已上传'), ('preview', '预览中'), ('validated', '已校验'), ('committed', '已入库'), ('failed', '失败'), ('processing', '处理中')], default='uploaded', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='importerrorrow',
            name='error_type',
            field=models.CharField(choices=[('format', '格式错误'), ('balance', '不平衡'), ('duplicate', '重复科目'), ('consistency', '期间不一致'), ('direction_mismatch', '方向异常'), ('closing_calculation', '期末计算差异'), ('foreign_currency', '外币校验异常'), ('mapping', '映射问题'), ('other', '其他')], max_length=20, verbose_name='错误类型'),
        ),
        migrations.AlterIndexTogether(
            name='importbatch',
            index_together={('project', 'period', 'import_type', 'is_active')},
        ),
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('import_type', models.CharField(choices=[('tb', '科目余额表'), ('je', '序时账')], max_length=10, verbose_name='导入类型')),
                ('file_extensions', models.JSONField(blank=True, default=list, verbose_name='适用文件扩展名')),
                ('header_signature', models.JSONField(blank=True, default=dict, verbose_name='表头特征指纹')),
                ('column_mapping', models.JSONField(blank=True, default=dict, verbose_name='列映射关系')),
                ('is_auto_saved', models.BooleanField(default=False, verbose_name='自动保存')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '映射模板',
                'verbose_name_plural': '映射模板',
                'db_table': 'imports_mapping_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('upload', '上传'), ('map', '映射'), ('validate', '校验'), ('commit', '提交'), ('delete', '删除'), ('activate', '激活'), ('remap', '重新映射'), ('export_errors', '导出错误')], max_length=20, verbose_name='操作类型')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='imports.importbatch', verbose_name='导入批次')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '导入日志',
                'verbose_name_plural': '导入日志',
                'db_table': 'imports_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_currency_code, reverse_backfill),
    ]
